### PR TITLE
New cava release: version 0.10.3

### PR DESCRIPTION
**Pull request by Dvd-Znf**
Cava version 0.10.3 was released yesterday  
https://github.com/karlstav/cava/releases/tag/0.10.3

### CODE REVIEW

**Comment by claymorwan** [comment]
Did they kinda forget about it or sum

**Comment by Dvd-Znf** [comment]
> Did they kinda forget about it or sum

idk TwT   
you can use the fork if you want the new version right now

**Comment by funilrys** [comment]
life's been busy

**Comment by funilrys** [comment]
btw, that's why I have GHA jobs ... I'll have to look into it ... GH keep disabling when no new version if available.

**Comment by funilrys** [comment]
I fixed the GHA jobs. It should work daily non-stop now.

**Comment by claymorwan** [comment]
OK so the build() keeps returning 
```
/usr/share/automake-1.17/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.17/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.17/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.17/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.17/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.17/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.17/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.17/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by Dvd-Znf** [comment]
> OK so the build() keeps returning
> 
> ```
> /usr/share/automake-1.17/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
> /usr/share/automake-1.17/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
> /usr/share/automake-1.17/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
> /usr/share/automake-1.17/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
> /usr/share/automake-1.17/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
> /usr/share/automake-1.17/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
> /usr/share/automake-1.17/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
> /usr/share/automake-1.17/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ```

Fixed by https://github.com/funilrys/aur-cava/pull/21
Try again and see if you still have this issue

**Comment by claymorwan** [comment]
Ya it's working now, thanks :3

**Pull request merged**
